shorturl/shorturl/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'urldispatch.views.home', name='home'),
    # url(r'^urldispatch/', include('urldispatch.foo.urls')),

    url(r'^$', 'urldispatch.views.home', name='home'),
    url(r'^add$', 'urldispatch.views.add', name='add'),
    url(r'^items$', 'urldispatch.views.your_items', name='items'),
    url(r'^edit/(?P<short_url>[a-zA-Z0-9_-]+)$', 'urldispatch.views.edit_url', name='edit'),
    url(r'^urlcheck$', 'urldispatch.views.urlcheck', name='urlcheck'),
    url(r'^urlcheck/shortname/(?P<short_url>[a-zA-Z0-9_-]+)$', 'urldispatch.views.urlcheck_shortname', name='urlcheck_shortname'),
    url(r'^(?P<short_url>[a-zA-Z0-9_-]+)$', 'urldispatch.views.redirect', name='redirect'),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

shorturl/urldispatch/models.py
from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.timezone import now

import urllib2
import socket

from urlparse import urlparse
from utils import test_url, get_destination_url


class Url(models.Model):
    username = models.CharField(max_length=50)

    short_url = models.CharField(max_length=50,primary_key=True)
    short_name = models.CharField(max_length=50,unique=True,null=True,blank=True)
    destination_url = models.CharField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    view_count = models.IntegerField(default=0)
    last_access = models.DateTimeField(null=True, blank=True)
    active = models.BooleanField(default=True)

    status_last_working = models.DateTimeField(null=True, blank=True, help_text="Last time url was accessible")
    status_working_since = models.DateTimeField(null=True, blank=True, help_text="URL has been accessible from this date")
    status_last_fail = models.DateTimeField(null=True, blank=True, help_text="Last time URL was not accessible")
    status_current = models.BooleanField(default=False, help_text="Current status")
    status_last_error = models.TextField(null=True, blank=True, help_text="Last error message")
    status_fail_count = models.IntegerField(default=0, help_text="Number of failures")

    class Meta:
        get_latest_by = "created"
        ordering = ["-created", "-modified"]

    def get_short_name(self):
        return "https://%s/%s" % (settings.SHORTURL_DOMAIN, self.short_name)

    def get_short_url(self):
        return "https://%s/%s" % (settings.SHORTURL_DOMAIN, self.short_url)

    def get_destination_url(self):
        return get_destination_url(self.destination_url)

    def test_url(self):
        data = test_url(self.get_destination_url())

        def fail(message):
            self.status_working_since = None
            self.status_last_fail = now()
            self.status_fail_count += 1
            self.status_current = False
            self.status_last_error = message
            self.save()

        def success():
            if self.status_current == False:
                self.status_working_since = now()
            self.status_last_working = now()
            self.status_current = True
            self.save()

        if data["status_current"]:
            success()
        else:
            fail(data["status_last_error"])

        for item in ["status_fail_count", "status_current", "status_last_error", "status_last_working", "status_last_fail", "status_working_since"]:
            data[item] = getattr(self, item)
        return data

    def validate_short_name(self, url, save=False):
        short_name = slugify(url)
        short_name_count = Url.objects.filter(short_name=short_name).count()
        short_url_count = Url.objects.filter(short_url=short_name).count()

        if short_name in settings.RESERVED_URLS:
            return "That URL is reserved"
        elif short_name != self.short_url and len(short_name) < 7:
            return "That's too short (<7 characters)"
        elif (short_name != self.short_name and short_name_count > 0) or (short_name != self.short_url and short_url_count > 0):
            return "Sorry! That URL already exists"
        else:
            if save:
                self.short_name = short_name
                self.save()
            return True

shorturl/urldispatch/forms.py
import django.forms as forms

class EditForm(forms.Form):
    short_name = forms.CharField()
    active = forms.BooleanField(required=False)

shorturl/urldispatch/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.forms.util import ErrorList
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.timezone import now
from django.views.decorators.http import require_http_methods, require_POST, require_safe

import datetime
import hashlib
import json
import math
import random

from decorators import *
from forms import EditForm
from models import Url
from utils import test_url, get_destination_url

@require_safe
@login_required
@render_to("home.html")
def home(request):
    return {}

def get_unique_id(url, username):
    """ Return new (saved) Url object with unique short URL """
    iteration = 0
    hdigest = "%s-%s" % (url, random.random())
    while True:
        hdigest = hashlib.sha512(hdigest).hexdigest()
        if iteration < 10:
            short_url = hdigest[0:4]
        else:
            length = 4 + int(math.sqrt(iteration - 10))
        if iteration == 100:
            raise Exception("Can't find unique shorturl")
        try:
            obj = Url.objects.create(short_url=short_url, short_name=short_url, username=username, destination_url=url)
            obj.save()
            return obj
        except IntegrityError:
            iteration += 1

@require_http_methods(["GET", "POST", "HEAD"])
@login_required
@render_to("edit.html")
def edit_url(request, short_url):
    username = request.user.username

    # Validation & authorization
    object = get_object_or_404(Url, short_url=short_url)
    if object.username != username:
        raise PermissionDenied("That's not your item")

    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            short_name = form.cleaned_data["short_name"]
            status = object.validate_short_name(short_name, True)
            if status == True:
                return HttpResponseRedirect(reverse("urldispatch.views.edit_url", args=(short_url,)))
            else:
                errors = form._errors.setdefault("short_name", ErrorList())
                errors.append(status)
    else:
        form = EditForm({"short_name": object.short_name, "active": object.active})

    return {"item": object, "form": form, "short_url": short_url}

@require_POST
@login_required
@ajax_request
def urlcheck_shortname(request, short_url):
    username = request.user.username
    url = request.POST.get("short_name", None)
    if not url:
        return { "valid": False }

    obj = get_object_or_404(Url, short_url=short_url)
    if obj.username != username:
        raise PermissionDenied("That's not your item")

    status = obj.validate_short_name(url)
    if status == True:
        return {"valid": True}
    return {"valid": False}        

@require_POST
@login_required
@ajax_request
def urlcheck(request):
    url = request.POST.get("long_url", None)
    if not url:
        return { "valid": False }
    status = test_url(get_destination_url(url))
    if status["status_current"]:
        return { "valid": True }
    return { "valid": False }


@require_POST
@login_required
@ajax_request
def add(request):
    username = request.user.username
    url = request.POST.get("long_url")
    if not url:
        return {"success": False, "message": "Invalid URL"}

    try:
        obj = Url.objects.get(destination_url=url, username=username)
    except Url.DoesNotExist:
        obj = get_unique_id(url, username)

    return {"success": True, "url": "http://%s/%s" % (settings.SHORTURL_DOMAIN, obj.short_url), "edit_url": "/edit/%s" % obj.short_url }

@require_safe
def redirect(request, short_url):
    item = get_object_or_404(Url, short_url=short_url)
    if not item.active:
        raise Http404
    item.last_access = now()
    item.view_count += 1
    item.save()
    return HttpResponseRedirect(item.get_destination_url())

@require_safe
@render_to("your_items.html")
def your_items(request):
    username = request.user.username
    items = Url.objects.filter(username=username).filter(active=True)
    return {"items": items}

shorturl/urldispatch/templates/base.html
{% load active %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>URL shortening</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="URL shortening service">
    <meta name="author" content="">
    <link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
    </style>
    <link href="/static/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
    <script type="text/javascript" src="/static/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap-tooltip.js"></script>
    <script type="text/javascript" src="/static/js/shorturl.js"></script>
    <script type="text/javascript" src="/static/js/underscore-min.js"></script>
    {% block header %}{%endblock%}
  </head>


 <body>

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li class="{% active request "^/$" %}"><a href="{% url home %}">Home</a></li>
          <li class="{% active request "^/items" %}"><a href="{% url items %}">Your URLs</a></li>
        </ul>
        <h3 class="muted">URL shortening</h3>
      </div>

      <hr>

	{% block content %}{% endblock %}

      <hr>

      <div class="footer">
        <p>&copy; Futurice Ltd 2012</p>
      </div>

    </div> <!-- /container -->

  </body>
</html>

shorturl/urldispatch/templates/edit.html
{% extends "base.html" %}

{% block header %}
<script type="text/javascript">
var validity_ajax;
function set_vd_class(add_class, title) {
 var vd = $("#validity-status");
 vd.removeClass().addClass(add_class);
 $("#url_validation_status").data("tooltip").options.title = title;
}

function check_url_validity() {
 if (typeof validity_ajax != "undefined") {
  validity_ajax.abort();
 }
 set_vd_class("icon-refresh", "Refreshing...");
 short_name = $("#id_short_name").val();

 validity_ajax = $.ajax({
    type: "POST",
    url: "{% url urlcheck_shortname item.short_url %}",
    data: {"short_name": short_name},
    timeout: 2000,
    success: function(data) {
     if (data.valid) {
       set_vd_class("icon-ok-sign", "Short name is valid");
     } else {
       set_vd_class("icon-remove-sign", "Short name is invalid");
     }
    },
    error: function() {
     set_vd_class("icon-exclamation-sign", "An error occured");
    },
    dataType: "json"
 });
}

var lazy_url_validity = _.debounce(check_url_validity, 250);

$(document).ready(function() {
 $("#url_validation_status").tooltip({title: "URL validation"});
 $("#id_short_name").keyup(function() {
  lazy_url_validity();
 });
});

</script>
{% endblock %}

{% block content %}

<h2>Item: <a href="{{ item.get_short_url }}">{{ item.get_short_url }}</a></h2>

{% ifnotequal item.short_url item.short_name %}
<p>Alternatively, <a href="{{ item.get_short_name }}">{{ item.get_short_name }}</a></p>
{% endifnotequal %}

{% if item.status_current %}
<p><a href="{{ item.get_destination_url }}">Destination URL</a> is up since {{ item.status_working_since }}.</p>
{% else %}
 {% if item.status_last_error %}
  <p><a href="{{ item.get_destination_url }}">Destination URL</a> is down{% if item.status_last_working %} since {{ item.status_last_working }}{% endif %}. Error recorded is <code>{{ item.status_last_error }}</code></p>
 {% else %}
  <p><a href="{{ item.get_destination_url }}">Destination URL</a> status is unknown.</p>
 {% endif %}
{% endif %}

<form method="post" action="{% url edit short_url %}">
{% csrf_token %}
<p><label for="id_subject">Short name:</label>

{{ form.short_name.errors }}
<div class="input-append">
  {{ form.short_name }}
  <span id="url_validation_status" class="add-on"><i id="validity-status" class="icon-question-sign"></i></span>
</div>


</p>

<input style="display:none" checked="checked" type="checkbox" name="active" id="id_active" />

<p>
<a href="{% url items %}" class="btn">Back</a>
<input type="submit" value="Save" class="btn btn-primary">
</p>

</form>
{% endblock %}

shorturl/urldispatch/templates/home.html
{% extends "base.html" %}

{% block header %}
<script type="text/javascript">
var validity_ajax;
function set_vd_class(add_class, title) {
 var vd = $("#validity-status");
 vd.removeClass().addClass(add_class);
 $("#url_validation_status").data("tooltip").options.title = title;
}

function check_url_validity() {
 if (typeof validity_ajax != "undefined") {
  validity_ajax.abort();
 }
 set_vd_class("icon-refresh", "Refreshing...");
 long_url = $("#long_url").val();
 if (long_url.length < 4) {
  return;
 }
 validity_ajax = $.ajax({
    type: "POST",
    url: "/urlcheck",
    data: {"long_url": long_url},
    timeout: 2000,
    success: function(data) {
     if (data.valid) {
       set_vd_class("icon-ok-sign", "URL is valid and reachable");
     } else {
       set_vd_class("icon-remove-sign", "URL is invalid or not reachable");
     }
    },
    error: function() {
     set_vd_class("icon-exclamation-sign", "An error occured");
    },
    dataType: "json"
 });
}

var lazy_url_validity = _.debounce(check_url_validity, 250);

$(document).ready(function() {
 $("#url_validation_status").tooltip({title: "URL validation"});
 var ab = $("#shorten");
 $("#shorten").prop("disabled", true);
 $("#long_url").keyup(function() {
  $("#shortened_url").hide("fast");
  if ($(this).val().length > 4) {
   ab.prop("disabled", false);
   ab.html("Go!");
   lazy_url_validity();
  } else if ($(this).val().length == 0) {
   ab.prop("disabled", true);
   ab.html("Go!");
  } else {
   ab.prop("disabled", true);
   ab.html("Too short");
  }
 });

 $("#short_url").click(function() {
  $(this).select();
 });

 $("#shorten").click(function() {
  ab.prop("disabled", true);
  ab.html("Loading...");
  var long_url = $("#long_url").val();
  $.ajax({
    type: "POST",
    url: "/add", 
    timeout: 5000,
    data: {"long_url": long_url}, 
    success: function(data, textStatus) {
      ab.prop("disabled", false);
      ab.html("Go!");
      if (data.success == false) {
        $("#warning-message").html(data.message);
        $("#warning-message-box").show("fast");
      } else {
        $("#warning-message-box").hide("fast");
        $("#shortened_url").show("fast");
        $("#short_url").val(data.url);
        $("#short_url").focus().select();
        $("#edit_short_url").attr("href", data.edit_url);
      }
    },
    dataType: "json",
    error: function(jqXHR, textStatus, errorThrown) {
       $("#warning-message").html("An error occured. "+errorThrown);
       $("#warning-message-box").show("fast");
       ab.prop("disabled", false);
       ab.html("Go!");
    }
  });
 });
});
</script>

{% endblock %}
{% block content %}
      <div class="jumbotron">
        <h1>Paste URL</h1>

<div id="warning-message-box" class="alert" style="display:none">
  <strong>Warning!</strong> <span id="warning-message"></span>
</div>


<p>
<div class="input-append">
  <input class="span4" id="long_url" type="text" placeholder="Paste URL">
  <span id="url_validation_status" class="add-on"><i id="validity-status" class="icon-question-sign"></i></span>
</div>
</p>
<p>
  <button id="shorten" class="btn" type="button">Go!</button>
</p>

<div id="shortened_url" style="display:none">
	<p>Shortened URL: </p>

	<p><input class="span4" id="short_url" type="text"> <a id="edit_short_url" href="#"><i class="icon-edit"></i></a></p>

</div>

</div>

{% endblock %}

shorturl/urldispatch/templates/your_items.html
{% extends "base.html" %}

{% block content %}

<table class="table table-hover">
<thead>
<tr>
<th></th>
<th>Shortened</th>
<th>Full URL</th>
<th>Created</th>
<th>Views</th>
</tr>
</thead>
<tbody>
{% for item in items %}
<tr>
<td><a href="{% url edit item.short_url %}"><i class="icon-edit"></i></a></td>
<td><a href="{{ item.get_short_url }}">{{ item.get_short_url }}</a></td>
<td>{{ item.destination_url|truncatechars:50 }}</td>
<td>{{ item.created }}</td>
<td>{{ item.view_count }}</td>
</tr>
{% empty %}
<tr>
<td colspan="5">Sorry, you don't have any items. Why don't you go to <a href="{% url home %}">add something?</a></td>
</tr>
{% endfor %}
</tbody>
</table>

{% endblock %}